# Generated by Django 2.0.5 on 2018-05-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='note',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
